[package]
name = "noise_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
blist = "0.0.4"
serde = { version = "1.0.158", features = ["derive"] }
